name: Release from Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version from pubspec.yaml
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Extract changelog for current version
        run: |
          version="## ${{ steps.version.outputs.version }}"
          awk -v version="$version" '
            $0 == version {found=1; next}
            /^## / && found {exit}
            found {print}
          ' CHANGELOG.md > changelog_excerpt.md

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body_path: changelog_excerpt.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
